name: Build and Push Docker Images

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Images
        env:
          IMAGE1: frontend
          IMAGE2: backend
          REPOSITORY_TAG1: ${{ secrets.DOCKERHUB_USERNAME }}/frontend
          REPOSITORY_TAG2: ${{ secrets.DOCKERHUB_USERNAME }}/backend
        run: |
          docker build -t $REPOSITORY_TAG1 frontend/
          docker push $REPOSITORY_TAG1
          docker build -t $REPOSITORY_TAG2 backend/
          docker push $REPOSITORY_TAG2
